-- Tabla
CREATE TABLE PERSONA (
    ID_PERSONA NUMBER(10) DEFAULT PERSONA_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(200) NOT NULL, 
    CORREO VARCHAR2(150) UNIQUE NOT NULL,
    CELULAR VARCHAR2(20) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_ACTUALIZACION DATE
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) DEFAULT USUARIO_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100) UNIQUE NOT NULL,
    CONTRASENIA VARCHAR2(200) NOT NULL, 
    ID_PERSONA NUMBER(10) NOT NULL,
    ID_ORIGEN NUMBER(2) NOT NULL,
    ACTIVO NUMBER(1) NOT NULL,
    BLOQUEO NUMBER(1) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_BLOQUEO DATE,
    FECHA_ACTUALIZACION DATE
);

CREATE TABLE ORIGEN (
    ID_ORIGEN NUMBER(2) DEFAULT ORIGEN_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100) UNIQUE NOT NULL,
    CLAVE VARCHAR2(10) NOT NULL,
    ESTATUS NUMBER(1) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_ACTUALIZACION DATE
);

CREATE TABLE SESION (
    ID_SESION NUMBER(10) DEFAULT SESION_SEQ.NEXTVAL PRIMARY KEY,
    ID_USUARIO NUMBER(10) NOT NULL,
    JTI VARCHAR(200) UNIQUE NOT NULL,
	ACTIVO NUMBER(1) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_EXPIRACION DATE NOT NULL,
    FECHA_ACTUALIZACION DATE
);

CREATE TABLE SEGUNDO_FA (
	ID_SEGUNDO_FA NUMBER(10) DEFAULT SEGUNDO_FA_SEQ.NEXTVAL PRIMARY KEY,
    ID_USUARIO NUMBER(10) NOT NULL,
    SECRETO VARCHAR(64) NOT NULL,
	ACTIVO NUMBER(1) NOT NULL,
	FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_ACTUALIZACION DATE
);

-- Secuencia
CREATE SEQUENCE PERSONA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE USUARIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE ORIGEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SESION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
	
CREATE SEQUENCE SEGUNDO_FA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

INSERT INTO ORIGEN(NOMBRE, CLAVE, ESTATUS) VALUES
('App Movil', 'App', 1);

SELECT * FROM PERSONA;
SELECT * FROM USUARIO;
SELECT * FROM ORIGEN;
DESCRIBE USUARIO;


DROP TABLE PERSONA;
DROP TABLE USUARIO;
DROP TABLE ORIGEN;

ALTER TABLE USUARIO MODIFY ID_USUARIO DEFAULT USUARIO_SEQ.NEXTVAL;

DELETE PERSONA;
DELETE USUARIO;
ALTER SEQUENCE USUARIO_SEQ RESTART START WITH 1;